#!/usr/bin/env python3

import argparse
import os
from snippets.syntax import *
from colorama import *




def parse():
    parser = argparse.ArgumentParser(description='')

    


    parser.add_argument(
                    "lang",
                        type=str.lower,
                        help='The snippets language.',)
    parser.add_argument(
                        "snippet",
                        type=str.lower,
                        help='The code snippet you want to display.',)

    args = parser.parse_args() 

    process(args)


def process(args):
    dirname = os.path.dirname(__file__)

    try:        
        l = (dirname + "/snippets/" + args.lang + "/" + args.snippet + ".txt")
        f = open(l, 'r') #Open snippet
        print(highlight(f.read())) #Highlight and print
        f.close()
    except Exception as e:
        print(e)                                        




if __name__ == "__main__":

    parse()






